SELECT SEAT_ID FROM
(
    SELECT SEAT_ID,
    SEAT_ID - LAG(SEAT_ID,1) OVER (order by SEAT_ID) AS LAG_DIFF ,
    LEAD(SEAT_ID, 1) OVER (order by SEAT_ID)- SEAT_ID AS LEAD_DIFF
    FROM CINEMA
    WHERE FREE = 1
) X
WHERE LAG_DIFF=1 OR LEAD_DIFF=1
